[theme]
primaryColor = "#002F9D"
backgroundColor = "#181D1F"
secondaryBackgroundColor = "#222628"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true
runOnSave = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 10000
maxMessageSize = 10000
enableWebsocketCompression = false
enableStaticServing = false
folderWatchBlacklist = ""

[runner]
magicEnabled = false
fastReruns = true
enforceSerializableSessionState = false
enumCoercion = "nameOnly"

[browser]
gatherUsageStats = false